name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render API
        run: curl -s https://harita-projesi.onrender.com/api > /dev/null
